	MEDIC( HeroSubClass.SAVIOR, HeroSubClass.THERAPIST, HeroSubClass.MEDICALOFFICER ),
	ARCHER( HeroSubClass.BOWMASTER, HeroSubClass.JUGGLER, HeroSubClass.SHARPSHOOTER ),
	NECROMANCER( HeroSubClass.WARLOCK, HeroSubClass.DEATHKNIGHT, HeroSubClass.WIZARD );